### ISSUE TITLE
Standardize formatting of RFC2119 language

### ISSUE THREAD

**Issue by leonardr** [opds-community/drafts#17]
The OPDS 1.2 spec uses both MUST and _must_ format when invoking RFC2119. We should consistently use one or the other.

**Comment by HadrienGardeur** [comment]
@leonardr 

I've just fixed the one reference that I could find. Do you have any additional examples?

**Comment by leonardr** [comment]
I guess it was just the one case. Sorry, I thought there were more or I would have made the change myself.
