### ISSUE TITLE
JSON Schema - link missing bitrate, because out-of-date duplicate of Readium webpub manifest schema

### ISSUE THREAD

**Issue by danielweck** [opds-community/drafts#20]
ReadiumWebPubManifest link:
https://github.com/readium/webpub-manifest/blob/ca6d887caa2d0495200fef4695f41aacb5fed2e9/schema/link.schema.json

OPDS2 link (only difference: `properties` object ... and of course missing `bitrate`):
https://github.com/opds-community/drafts/blob/4d82fb9a64f35a174a5f205c23ba623ec010d5ec/schema/link.schema.json

So, would it be possible for `@OPDS/link.schema.json` to "extend" `@RWPM/link.schema.json` in order to automatically inherit the common JSON dictionary fields, and then add the domain-specific `properties` object? This would avoid "out of sync" problems, and would make the JSON Schema more readable / maintainable.

Related issue: https://github.com/readium/webpub-manifest/issues/16

**Comment by danielweck** [comment]
Note that the TypeScript implementation currently uses the "extend" method, so OPDS links are allowed to carry the `bitrate` attribute, but of course the current JSON Schema would report a validation error.

**Comment by danielweck** [comment]
Related issue: https://github.com/opds-community/drafts/issues/21

**Comment by danielweck** [comment]
Similar issue: https://github.com/opds-community/drafts/issues/25

**Comment by HadrienGardeur** [comment]
This was changed in a recent commit: https://github.com/opds-community/drafts/commit/87d530e05f001a5030ae3a1936bf6b9249d79773
