### ISSUE TITLE
JSON Schema - publication.images (link[]) should reference ReadiumWebPubManifest link schema?

### ISSUE THREAD

**Issue by danielweck** [opds-community/drafts#22]
The OPDS `publication` schema introduces `links[]`, which reference the OPDS domain-specific `link` (with its additional well-defined `properties`):

https://github.com/opds-community/drafts/blob/4d82fb9a64f35a174a5f205c23ba623ec010d5ec/schema/publication.schema.json#L10
=>
https://github.com/opds-community/drafts/blob/4d82fb9a64f35a174a5f205c23ba623ec010d5ec/schema/link.schema.json

Same with `feed` `link[]`, of course:
https://github.com/opds-community/drafts/blob/2d027051a725ae62defdc7829b597564e5b8e9e5/schema/feed.schema.json#L11

But, what about `images[]`? Shouldn't this reference the ReadiumWebPubManifest `link` schema? There is really no need for the OPDS-specific `properties` in the case of images, right? (e.g. `price`, `numberOfItems`, etc.)
https://github.com/opds-community/drafts/blob/4d82fb9a64f35a174a5f205c23ba623ec010d5ec/schema/publication.schema.json#L52
=>
https://github.com/readium/webpub-manifest/blob/ca6d887caa2d0495200fef4695f41aacb5fed2e9/schema/link.schema.json
?

**Comment by HadrienGardeur** [comment]
This was changed in a recent commit: https://github.com/opds-community/drafts/commit/87d530e05f001a5030ae3a1936bf6b9249d79773
