### ISSUE TITLE
Feature request: bookmarks and annotations

### ISSUE THREAD

**Issue by FedericoCeratto** [opds-community/drafts#27]
Hello and thanks for developing OPDS 2.0
It would be really nice to optionally support setting and fetching the current page, bookmarks and perhaps text annotations.
They could be 3 different types of data so that setting and getting the current page can be done across devices with little network traffic.
Readers should list books with current page > 0 under a "currently reading" list.
Current page set to 0 or dedicated flag could be used to list books as "reading list"
Current page set to the last page or dedicated flag indicates that the book reading is finished.

**Comment by Fmstrat** [comment]
@FedericoCeratto Looks like you beat me to the punch in migrating a conversation from last year over here. Recommend closing this issue and joining into https://github.com/opds-community/drafts/issues/28

Thanks!

**Comment by FedericoCeratto** [comment]
Moving conversation to #28
