### ISSUE TITLE
thr:count in OPDS1 XML, what is the equivalent in OPDS2?

### ISSUE THREAD

**Issue by danielweck** [opds-community/drafts#30]
`thr:count` attribute (`xmlns:thr="http://purl.org/syndication/thread/1.0"`) on `entry` `link`, for example:

`<link type="application/atom+xml;profile=opds-catalog;kind=navigation" rel="subsection" thr:count="21708" href="https://catalog.feedbooks.com/store/browse/en/top.atom?cat=FBJUV000000"/>`

https://catalog.feedbooks.com/category/FBFIC000000/sub.atom

**Comment by HadrienGardeur** [comment]
You can use `numberOfItems`, as illustrated in https://catalog.feedbooks.com/store/browse/fr/recent.json?cat=FBFIC019000

It's mentioned in the current draft under https://drafts.opds.io/opds-2.0#14-facets

> may contain numberOfItems in the properties of a Link Object to hint at the number of publications available for a given facet

**Comment by danielweck** [comment]
Thanks Hadrien. I've fixed the OPDS 1 > 2 converter to handle cases other than facets.
