### ISSUE TITLE
Images should not be required in OPDS publications

### ISSUE THREAD

**Issue by llemeurfr** [opds-community/drafts#52]
Images are required in OPDS publications as per the [OPDS 2 spec](https://drafts.opds.io/opds-2.0#12-publications). More, the collection must contain at least one item as per the JSON schema (which is not an explicit requirement in the spec). 

But we have a use case where OPDS publications are generated from DAISY publication, which have no cover image. They are consumed from a smart speaker client which has no screen. Adding a dumb image is not good practice.

**Comment by HadrienGardeur** [comment]
I agree with this statement and I'll open a specific PR to lower this requirement to a SHOULD.

**Comment by HadrienGardeur** [comment]
Closing this issue now that we have an open PR to discuss this matter.
