### ISSUE TITLE
OPDS 2 Spec should have terminology and conformance sections numbered under Overview

### ISSUE THREAD

**Issue by barmintor** [opds-community/drafts#54]
- Overview should be a numbered heading
- Overview section should have subsections for Terminology and Conformance Statements
- Conformance Statements should refer to RFC2119
- Other sections should be renumbered

**Comment by HadrienGardeur** [comment]
All good points @barmintor, I'll bring this up to par with the OPDS 1.x spec in the upcoming weeks.
