### ISSUE TITLE
OpenSearch description links in OPDS 1.2 spec no longer resolve

### ISSUE THREAD

**Issue by barmintor** [opds-community/drafts#57]
The ElasticSearch/Kibana fork's website returns a 404 for http://www.opensearch.org/Specifications/OpenSearch/1.1

As far as I can tell, the only live link would be to https://github.com/dewitt/opensearch/blob/master/opensearch-1-1-draft-6.md

**Comment by HadrienGardeur** [comment]
Fixed in https://github.com/opds-community/specs/commit/f5b7de818afcfbb9f4906ce21a43995ea0232827
