### ISSUE TITLE
OPDS Identifier Practice

### ISSUE THREAD

**Issue by barmintor** [opds-community/drafts#65]
From the Palace Project slack:

One of the obstacles to broader integration between Palace and our other systems is the difficulty in pulling the identifiers that our other workflows are based on through the circ manager ingest and catalog publication. In particular, ISBNs and MARC organization-scoped control numbers (001+003, 010, 016, 035) without relying on them being encoded in the single URI identifier for a publication.

The use of [schema.org](http://schema.org/) properties provides a way through this for ISBN/ISSN, and there's a merged PR for this in the parser Palace uses for the publication manifests (though the data is not yet operated on by the CM, to my knowledge). The organization-scoped control number are more complicated.

schema:identifier technically has a domain of 3 data types: text (supported), URI (supported), and PropertyValue (no support). PropertyValue is an object value that could be used to model the MARC control numbers. We could pursue this by trying to get [schema.org](http://schema.org/) to have an identifier sub-property for bibframe:Local (which is how those MARC fields are modeled there, with a value and associated assigner property pointing to the MARC org as a URI), or we could simply document a practice for including these control numbers as PropertyValue (with a nested assigner property and, for purposes of completeness, schema:supersedes for replaced values.

**Comment by barmintor** [comment]
@HadrienGardeur you mentioned an idea about how to mark up control numbers with institutional codes in OPDS - do you have an example in mind?

**Comment by HadrienGardeur** [comment]
I was mostly talking about schemes for subjects: BISAC or Thema. I don't remember discussing anything related to publication identifiers aside from the usual URN prefix.

**Comment by HadrienGardeur** [comment]
There's an on-going discussions at #79 so I'm marking this issue as a duplicate and closing it.
